name: nf-core-eager-2.0.7dev
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - anaconda::openjdk=8.0.152
  - bioconda::fastqc=0.11.8
  - bioconda::adapterremoval=2.2.2
  - bioconda::adapterremovalfixprefix=0.0.4
  - bioconda::bwa=0.7.17
  - bioconda::picard=2.19.0
  - bioconda::samtools=1.9
  - bioconda::dedup=0.12.5
  - bioconda::angsd=0.923
  - bioconda::circularmapper=1.93.4
  - bioconda::gatk4=4.1.1.0
  - bioconda::qualimap=2.2.2b
  - bioconda::vcf2genome=0.91
  - bioconda::damageprofiler=0.4.5
  - bioconda::multiqc=1.7
  - bioconda::pmdtools=0.60
  - conda-forge::r-rmarkdown=1.12
  - conda-forge::libiconv=1.15
  - conda-forge::pigz=2.3.4
  - bioconda::sequencetools=1.2.2
  - bioconda::preseq=2.0.3
  - bioconda::fastp=0.19.7
  - bioconda::bamutil=1.0.14
  - bioconda::mtnucratio=0.5
  - pysam=0.15.2
  - python=3.6.7
  #Missing Schmutzi,snpAD
